---
title: "Extreme Weather Events and Voting"
format: html
jupyter: true
---

# Introduction

blablabla

## Catnat dataset

```{r}
# if (!requireNamespace("tidyverse", quietly = TRUE)) install.packages("tidyverse")
# if (!requireNamespace("ggplot2", quietly = TRUE)) install.packages("ggplot2")
# if (!requireNamespace("gganimate", quietly = TRUE)) install.packages("gganimate")
# if (!requireNamespace("gifski", quietly = TRUE)) install.packages("gifski")
# if (!requireNamespace("ggplotify", quietly = TRUE)) install.packages("ggplotify")
# if (!requireNamespace("fixest", quietly = TRUE)) install.packages("fixest")

library(tidyverse)
library(ggplot2)
library(gganimate)
library(gifski)
library(ggplotify)
library(fixest)

df_catnat <- read.csv("../data/catnat_gaspar_mandat_legis.csv", sep = ";")
df_catnat <- df_catnat %>% mutate(Year = as.Date(election, format = "%Y-%m-%d"))
#election is now an integer in df_catnat
df_catnat$Year <- as.integer(format(df_catnat$Year, "%Y"))


df_legis <- read.csv("../data/legislatives.csv", sep = ",")




# #change the name codcommune in codecommune in dfcatnat
df_catnat <- df_catnat %>% rename(codecommune = cod_commune)
df_catnat$codecommune <- as.character(df_catnat$codecommune)
df_legis$codecommune <- as.character(df_legis$codecommune)
#for the codecommune with only 4 digits, add 0 in front of the codecommune
df_legis$codecommune <- ifelse(nchar(df_legis$codecommune) == 4, paste0("0", df_legis$codecommune), df_legis$codecommune)

#merge df_catnat and df_legis on codecommune and election

df_legis <- df_legis %>% left_join(df_catnat, by = c("codecommune" , "Year"))
#calculate the national share of each party
df_legis <- df_legis %>% group_by(Year, vote_type) %>% mutate(national_share = sum(share * votants)/sum(votants)) %>% ungroup()

full_rev <- read.csv("../data/revenu.csv", sep = ",")
full_rev <- full_rev %>% rename(codecommune = CODGEO)
full_rev$codecommune <- as.character(full_rev$codecommune)
full_rev <- full_rev %>% filter(Year == 2017)
#drop Year from full_ref
full_rev <- full_rev %>% select(-Year)

df_legis <- df_legis %>% left_join(full_rev, by = c("codecommune"))

#make a column city if Population > 10000, else rural
df_legis <- df_legis %>% mutate(city = ifelse(Population > 10000, "city", "rural"))

#print the national share of each party, and elections
library(ggplot2)

# Plot the national share by Year and vote_type
df_legis %>%
    group_by(Year, vote_type) %>%
    summarise(national_share = unique(national_share))
```


```{r}
data <- df_legis %>%
    filter(vote_type == "D") %>%
    select(codecommune, Year, share, mandat, mandat_2, mandat_4, Med_Niveau_vie, Gini, Population, dep, city, absention, Pop_bac, Pop_Sup5) %>%
    ungroup()

#normalize Gini mandat_2 and Med_Niveau_vie


#fill Nan in mandat_2 mandat and mandat_4 with 0
data$mandat_2[is.na(data$mandat_2)] <- 0
data$mandat[is.na(data$mandat)] <- 0
data$mandat_4[is.na(data$mandat_4)] <- 0
#remove NA from data
data <- data %>% filter(!is.na(share) & !is.na(mandat_2) & !is.na(Med_Niveau_vie))

# data <- data %>%
#     mutate(Med_Niveau_vie = (Med_Niveau_vie - min(Med_Niveau_vie)) / (max(Med_Niveau_vie) - min(Med_Niveau_vie)),
#               share = (share - min(share)) / (max(share) - min(share)))

data <- data %>%
    mutate(Med_Niveau_vie_sq = Med_Niveau_vie^2)



#mandat_2 becomes a boolean is mandat_2 > 0
data <- data %>% mutate(mandat_2 = ifelse(mandat_2 > 0, 1, 0))


model <- feols(share ~ mandat_2 | codecommune + Year , data)
summary(model)

```



### For the reelection of the mayors


```{r}
library(tidyverse)
library(ggplot2)
library(gganimate)
library(gifski)
library(ggplotify)
library(fixest)

df_catnat <- read.csv("../data/catnat_gaspar_mandat_muni.csv", sep = ";")
df_catnat <- df_catnat %>% mutate(Year = as.Date(election, format = "%Y-%m-%d"))
#election is now an integer in df_catnat
df_catnat$Year <- as.integer(format(df_catnat$Year, "%Y"))


df_reelec <- read.csv("../data/reelection_muni.csv", sep = ",")

#print the first 10 rows of df_reelec
head(df_reelec, 1)

head(df_catnat, 1)
# #change the name codcommune in codecommune in dfcatnat
df_catnat <- df_catnat %>% rename(codecommune = cod_commune)
df_reelec <- df_reelec %>% rename(codecommune = GEO_INSEE)
df_catnat$codecommune <- as.character(df_catnat$codecommune)
df_reelec$codecommune <- as.character(df_reelec$codecommune)
#for the codecommune with only 4 digits, add 0 in front of the codecommune
df_reelec$codecommune <- ifelse(nchar(df_reelec$codecommune) == 4, paste0("0", df_reelec$codecommune), df_reelec$codecommune)

#merge df_catnat and df_reelec on codecommune and election

df_reelec <- df_reelec %>% left_join(df_catnat, by = c("codecommune" , "Year"))
#calculate the national share of each party


full_rev <- read.csv("../data/revenu.csv", sep = ",")
full_rev <- full_rev %>% rename(codecommune = CODGEO)
full_rev$codecommune <- as.character(full_rev$codecommune)
full_rev <- full_rev %>% filter(Year == 2017)
#drop Year from full_ref
full_rev <- full_rev %>% select(-Year)

df_reelec <- df_reelec %>% left_join(full_rev, by = c("codecommune"))

#make a column city if Population > 10000, else rural
df_reelec <- df_reelec %>% mutate(city = ifelse(Population > 10000, "city", "rural"))
df_reelec$dep <- substr(df_reelec$codecommune, 1, 2)
```


```{r}
data <- df_reelec %>%
    select(codecommune, Year, reelected_2020, mandat, mandat_2, mandat_4, Med_Niveau_vie, Gini, Population, dep, city, Pop_bac, Pop_Sup5) %>%
    ungroup()

#normalize Gini mandat_2 and Med_Niveau_vie


#fill Nan in mandat_2 mandat and mandat_4 with 0
data$mandat_2[is.na(data$mandat_2)] <- 0
data$mandat[is.na(data$mandat)] <- 0
data$mandat_4[is.na(data$mandat_4)] <- 0
#remove NA from data
data <- data %>% filter(!is.na(reelected_2020) & !is.na(mandat_2) & !is.na(Med_Niveau_vie))

# data <- data %>%
#     mutate(Med_Niveau_vie = (Med_Niveau_vie - min(Med_Niveau_vie)) / (max(Med_Niveau_vie) - min(Med_Niveau_vie)),
#               share = (share - min(share)) / (max(share) - min(share)))

data <- data %>%
    mutate(Med_Niveau_vie_sq = Med_Niveau_vie^2)



#mandat_2 becomes a boolean is mandat_2 > 0
data <- data %>% mutate(mandat_2 = ifelse(mandat_2 > 0, 1, 0))


model <- feols(reelected_2020 ~ Pop_bac + mandat_2 | dep , data)
summary(model)
```